name: 'cymbal_fraud_pipeline'
version: '1.0.0'
config-version: 2

profile: 'cymbal_fraud'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  cymbal_fraud_pipeline:
    staging:
      +materialized: view
      +schema: transactions_dataset_evals
    marts:
      +materialized: table
      +schema: transactions_dataset_evals
